
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 30 00:03:51 CST 2025
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class SymSintax {
  /* terminals */
  public static final int Op_relacional = 21;
  public static final int Protect = 44;
  public static final int Llave_c = 28;
  public static final int Op_booleano = 24;
  public static final int Llave_a = 27;
  public static final int If = 10;
  public static final int Void = 33;
  public static final int Clase = 39;
  public static final int Static = 32;
  public static final int Default = 42;
  public static final int Interface = 41;
  public static final int Else = 11;
  public static final int Enum = 40;
  public static final int Corchete_c = 30;
  public static final int Corchete_a = 29;
  public static final int While = 13;
  public static final int Division = 19;
  public static final int Int = 8;
  public static final int Cadena = 9;
  public static final int Float = 5;
  public static final int Parentesis_c = 26;
  public static final int Parentesis_a = 25;
  public static final int For = 14;
  public static final int P_coma = 35;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Private = 43;
  public static final int Linea = 2;
  public static final int Char = 6;
  public static final int Op_atribucion = 22;
  public static final int ERROR = 38;
  public static final int Do = 12;
  public static final int Op_logico = 20;
  public static final int Public = 31;
  public static final int Identificador = 36;
  public static final int Resta = 17;
  public static final int Doub = 4;
  public static final int Bool = 7;
  public static final int Multiplicacion = 18;
  public static final int Op_incremento = 23;
  public static final int Numero = 37;
  public static final int Suma = 16;
  public static final int Main = 34;
  public static final int Igual = 15;
  public static final int Comillas = 3;
}

