
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 29 22:39:57 CST 2025
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 30;
  public static final int Class = 17;
  public static final int Protect = 23;
  public static final int Llave_c = 38;
  public static final int Op_booleano = 32;
  public static final int Llave_a = 37;
  public static final int If = 8;
  public static final int Void = 15;
  public static final int Clase = 20;
  public static final int Static = 14;
  public static final int Default = 22;
  public static final int Interface = 18;
  public static final int Else = 9;
  public static final int Enum = 19;
  public static final int Corchete_c = 42;
  public static final int Corchete_a = 41;
  public static final int While = 11;
  public static final int Division = 29;
  public static final int Int = 2;
  public static final int Parentesis_c = 36;
  public static final int Cadena = 7;
  public static final int Float = 3;
  public static final int Parentesis_a = 35;
  public static final int For = 12;
  public static final int P_coma = 39;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Private = 21;
  public static final int Char = 6;
  public static final int Op_atribucion = 31;
  public static final int ERROR = 24;
  public static final int Do = 10;
  public static final int Op_logico = 33;
  public static final int Public = 13;
  public static final int Identificador = 43;
  public static final int Resta = 27;
  public static final int Doub = 4;
  public static final int Bool = 5;
  public static final int Multiplicacion = 28;
  public static final int Op_incremento = 34;
  public static final int Numero = 44;
  public static final int Suma = 26;
  public static final int Main = 16;
  public static final int Igual = 25;
  public static final int Comillas = 40;
}

