
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 27 17:14:13 CST 2025
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 6;
  public static final int Parentesis_c = 27;
  public static final int For = 9;
  public static final int Parentesis_a = 26;
  public static final int Suma = 19;
  public static final int Numero = 33;
  public static final int Protect = 17;
  public static final int Op_booleano = 25;
  public static final int Identificador = 32;
  public static final int Comillas = 31;
  public static final int Int = 2;
  public static final int Default = 16;
  public static final int Llave_c = 29;
  public static final int Llave_a = 28;
  public static final int Op_relacional = 23;
  public static final int P_coma = 30;
  public static final int T_dato = 3;
  public static final int Main = 13;
  public static final int Cadena = 4;
  public static final int EOF = 0;
  public static final int Division = 22;
  public static final int Op_atribucion = 24;
  public static final int Resta = 20;
  public static final int If = 5;
  public static final int Private = 15;
  public static final int error = 1;
  public static final int Do = 7;
  public static final int Class = 14;
  public static final int Igual = 18;
  public static final int Void = 12;
  public static final int Public = 10;
  public static final int Multiplicacion = 21;
  public static final int Static = 11;
  public static final int While = 8;
}

